services:
  headscale:
    image: docker.io/headscale/headscale:0.26.0
    restart: unless-stopped
    container_name: headscale
    ports:
      - "0.0.0.0:8080:8080"
      - "0.0.0.0:9090:9090"
    volumes:
      # Please set <HEADSCALE_PATH> to the absolute path
      # of the previously created headscale directory.
      - $PWD/headscale/config:/etc/headscale
      - $PWD/headscale/lib:/var/lib/headscale
      - $PWD/headscale/run:/var/run/headscale
    command: serve

